eureka:
  client:
    service-url:
      defaultZone: http://localhost:8306/eureka  # Eureka Server地址
      register-with-eureka: true
      fetch-registry: true
server:
  port: 8087

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-route
          uri: lb://cloudloadbalancer
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: CustomFilterFactory
              args:
                headerName: X-My-Header
                headerValue: MyHeaderValue